version: '2'
services:
    conferencemanagement-app:
        image: conferencemanagement
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://conferencemanagement-postgresql:5432/ConferenceManagement
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    conferencemanagement-postgresql:
        extends:
            file: postgresql.yml
            service: conferencemanagement-postgresql
