version: '2'
services:
    conferencemanagement-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ConferenceManagement/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ConferenceManagement
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
